### ISSUE TITLE
Thanks and a question...

### ISSUE THREAD

**Issue by jagan999** [AseemWangoo/hands_on_kotlin#1]
Hello

Thanks for the nice tutorial. I am observing one issue. I have used StateFlow in my app instead of LiveData and saw that my list page was getting recomposed three times during the first load. I just couldn't put my finger on the reason and I assumed it might be an issue with StateFlow being a hot flow and this issue shouldn't there in your code that uses LiveData.

I downloaded your source code and added a log statement right after the items are loaded...like the below
    val items = mTodoViewModel.readAllData.observeAsState(listOf()).value
    Log.d("Todo", items.size.toString()) //Added this to check how many times the UI is recomposed

Running this gives the same behavior. The UI is recomposed EXACTLY 3 times just like in my code with StateFlow. 

Any insight on why this happens? I've tried all searches and forums but no one seems to talk about this.

**Comment by AseemWangoo** [comment]
In my opinion, I won't be worried about multiple rendering.

Reason: Before Jetpack Compose, we needed to call a setter on a widget (eg textview) etc which would change the state.
Once Compose was introduced, it gave us the flexibility to forget about setters.

Compose uses a concept called intelligent recomposition, where it only calls the functions that have changed.

Also attaching a screenshot from the official Android blog
![image](https://user-images.githubusercontent.com/16626254/127174782-4b647512-5393-4fc9-872d-e2d7e5cd3e63.png)

Link: https://developer.android.com/jetpack/compose/mental-model#recomposition

These are my simple thoughts :)

**Comment by jagan999** [comment]
Thanks for the prompt reply. I was concerned it might affect the performance. But what you say makes sense. I'll also read up the link you've mentioned. 

Interestingly, the view recomposes even if I removed all UI elements...so it still leaves me curious as to what's causing the re-rendering when nothing has changed...
