### ISSUE TITLE
Questions: saveToFile()

### ISSUE THREAD

**Issue by tmtben** [AseemWangoo/hands_on_kotlin#6]
Hello Aseem,

I've got questions about saveToFile function in your code:
Why to use `out` variable in addition to `outputFile`?
Why not to use `FileOutputStream(outputFile,**true**)` (true = append) to match with `outputFile.appendText(content)` logic?

Best regards,
Ben

**Comment by AseemWangoo** [comment]
That can also be done. Basically, this saveToFile snippet, I had copied from somewhere and then modified as per my need. :)
